version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/usr/src/node-app/
        working_dir: /usr/src/node-app/
        command: ["node", "dist/"]
