version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/var/www
        working_dir: /var/www
        command: ["node", "dist/"]
